name: flutter_document_picker
description: Allows user pick a document. Picked document is copied to app temporary directory. Optionally allows pick document with specific extension only.
version: 1.0.0
author: Tautvydas Å idlauskas <tautvydas.sidlauskas@gmail.com>
homepage: https://github.com/sidlatau/flutter_document_picker

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.sidlatau.flutterdocumentpicker
    pluginClass: FlutterDocumentPickerPlugin
